### ISSUE TITLE
[FEATURE] 模板预览时报错样式优化

### ISSUE THREAD

**Issue by xyjunco** [TencentBlueKing/bk-process-config-manager#150]
当前配置模板的预览时报错是使用 message 展示的，用户排查问题时不方便
希望修改成类似 IDE 编译台的错误信息展示方式

<img width="1245" alt="wecom-temp-1b1bf86d0c62587e4d1a0abccc94a3fb" src="https://user-images.githubusercontent.com/4710858/162697410-e2538609-a32d-4d43-b4a0-a78805d3a4d0.png">

设计稿：
http://idoc.ied.com/app/Q7xlujhJ/specs/design/j3hIjj6vh

**Comment by huazai-free** [comment]
1. 小于200px，是自适应高度的
2. 大于200px，默认显示200，用户可以滚动查看，也可以拉伸调整错误面板的比例
